version: '3.8'

services:
  polar-postgres:
    image: postgres:14.12
    container_name: polar-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: polardb_catalog
    ports:
      - "5432:5432"


volumes:
  pgdata:
